### ISSUE TITLE
Request for Source Code

### ISSUE THREAD

**Issue by SongyangChen2022** [yorkjiang1998/GTCAlign#1]
This task is interesting. Would it be possible to make the source code publicly available？

**Comment by yorkjiang1998** [comment]
Thanks for your liking, the code will be published as soon as the graph alignment framework is complete, and we will notify you by email.

**Comment by Longkaihuan** [comment]
Hello, this work provides a novel solution for the graph alignment problem and is worth researching. Could you please consider releasing the source code at your earliest convenience? It seems this work has been accepted for several months.

**Comment by yorkjiang1998** [comment]
Source code has been submitted

**Comment by yorkjiang1998** [comment]
> This task is interesting. Would it be possible to make the source code publicly available？

Source code has been submitted
