### ISSUE TITLE
Questions regarding the code

### ISSUE THREAD

**Issue by Longkaihuan** [yorkjiang1998/GTCAlign#2]
I encountered some issues while testing the code. Could you please provide the code for processing graph data into the centrality.npy file? In your code, the length of douban_s_centrality.npy becomes 1117, which doesn't match the 1118 nodes. If you could share the logic for handling this part of the code and for other datasets, it would be greatly helpful for our research. Thank you very much.

**Comment by 0graph0** [comment]
I encountered the same problem. Could you provide the code for processing other data sets in the paper? Thanks

**Comment by yorkjiang1998** [comment]
The number of nodes starts from 0. I can run it normally here. Can you post the error message when you run it? Let me help you look

**Comment by yorkjiang1998** [comment]
> I encountered some issues while testing the code. Could you please provide the code for processing graph data into the centrality.npy file? In your code, the length of douban_s_centrality.npy becomes 1117, which doesn't match the 1118 nodes. If you could share the logic for handling this part of the code and for other datasets, it would be greatly helpful for our research. Thank you very much.

The number of nodes starts from 0. I can run it normally here. Can you post the error message when you run it? Let me help you look

**Comment by 0graph0** [comment]
In the Douban dataset, there are four dictionaries constructed in douban_s_centrality.npy, each with a length of 1117. However, the offline graph of Douban has 1118 nodes, and it lacks centrality information for node ID 0. Therefore, I would like to provide you with the code logic to process the data and obtain the centrality.npy file.
