### ISSUE TITLE
The effectiveness of the global topology consistency matrix M

### ISSUE THREAD

**Issue by JacksOwO** [yorkjiang1998/GTCAlign#3]
In GTCAlign's paper, the principle of global topological consistency is a key point and a main contribution, and this graph alignment framework was developed based on this consistency. However, in the actual experimental process, it seems that the global topology consistency matrix M did not play a role, which is inconsistent with the description of the ablation experiments in the paper. In addition, according to the given data set file, one of the three real-world alignable networks(acm_dblp) did not produce the expected experimental results. 
![1705543293502](https://github.com/yorkjiang1998/GTCAlign/assets/144644704/ecc89a08-7d87-4020-b14f-4125171e4a46)
the result of GTC：
![1705543188803](https://github.com/yorkjiang1998/GTCAlign/assets/144644704/186778d2-6cf2-4543-be82-11e537c6d769)
the result of GTC w/o global topology consistency：
![1705543232736](https://github.com/yorkjiang1998/GTCAlign/assets/144644704/076280dd-e01d-4888-b441-2c9b352e24da)

**Comment by yorkjiang1998** [comment]
Our global topology information is constrained by two values in the code perspective, we did experiment at that time and it did work, in addition for the ACM_DBLP experiment, we have exactly the same effect, in response to your question above, the embedding dimension on the ACM_DBLP is 128 and the GTC value is 1.006, if you have any, please contact me email: yorkjpj@163.com.

**Comment by JacksOwO** [comment]
Thank you for your response; I have the following concerns:

The paper emphasizes the importance of the global topological matrix overall, but M only appears in the refinement process of top-k.
When we comment out the code for selecting candidate nodes using top-k (including the M matrix), we still achieve consistent accuracy as mentioned in the paper. This observation holds true for all three datasets. If there are doubts, please test your publicly available code.
Comparing your code to GAlign, it seems that the only difference is the removal of the loss function constructed by GAlign. The strategy of selecting accurate nodes to expand influence, especially in adjusting the weights of the adjacency matrix for better accuracy, shifts from a symmetric matrix to an asymmetric one. However, this contribution was originally proposed by GAlign and is just one aspect in other papers.
If my understanding is incorrect, please provide convincing results from ablation experiments; otherwise, I have reason to question the rationale behind the contributions of the entire paper.
![refine](https://github.com/yorkjiang1998/GTCAlign/assets/144644704/40711c99-c241-4b6a-a178-2649be477cc7)
![GTC](https://github.com/yorkjiang1998/GTCAlign/assets/144644704/5c5ee6b5-c56e-442b-b572-f64dc8589e64)

**Comment by yorkjiang1998** [comment]
Thank you for your reply, our code is improved on top of the previous framework code of graph-alignment, there are a lot of version files of the previous experiments, our public code is organized from the most original version, and our experiments at that time were really no problem. I will focus on checking the existing code, thanks for your reply and understanding!
